title: Steve S. Wilson
tagline: Personal Blog
description: >-
  Thoughts, notes, and updates.
url: "https://SteveSWilson.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Folders/files Jekyll should not process or copy into the built site.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - HOW_TO_ADD_A_POST.md
  - vendor/
  - node_modules/
